const PDFDocument = require("pdfkit");

const BRAND_COLOR = [231, 76, 60]; // #E74C3C coral red

/**
 * Generate a candidate report PDF.
 * Returns a Buffer.
 */
async function generateCandidateReport(candidate, job, org, options = {}) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const analysis = candidate.analysis || {};
    const isExternal = options.external || false;
    const color = org?.primaryColor || "#e74c3c";
    const companyName = org?.companyName || org?.name || "RecruitSmart";

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill(color);
    doc.fontSize(24).fillColor("#ffffff").text(companyName, 50, 25);
    doc.fontSize(12).text(isExternal ? "Candidate Assessment" : "Internal Candidate Report", 50, 52);

    doc.moveDown(3);
    doc.fillColor("#333333");

    // Candidate info
    doc.fontSize(18).text(candidate.name, { underline: true });
    doc.fontSize(11).fillColor("#666666");
    doc.text(`Position: ${job.title}`);
    doc.text(`Date: ${new Date().toLocaleDateString("en-GB")}`);
    if (analysis.currentRole) doc.text(`Current Role: ${analysis.currentRole}`);
    doc.moveDown();

    // Score
    const score = candidate.matchScore || 0;
    doc.fontSize(14).fillColor("#333333").text("Match Score");
    doc.fontSize(36).fillColor(score >= 75 ? "#10b981" : score >= 50 ? "#f59e0b" : "#ef4444");
    doc.text(`${score}/100`);
    doc.moveDown();

    // Summary
    if (analysis.candidateSummary) {
      doc.fontSize(14).fillColor(color).text("Summary");
      doc.fontSize(11).fillColor("#333333").text(analysis.candidateSummary);
      doc.moveDown();
    }

    // Score breakdown
    if (analysis.scoreBreakdown) {
      doc.fontSize(14).fillColor(color).text("Score Breakdown");
      const bd = analysis.scoreBreakdown;
      for (const [key, val] of Object.entries(bd)) {
        if (val && typeof val === "object") {
          doc.fontSize(11).fillColor("#333333");
          doc.text(`${key}: ${val.score}/100 (weight: ${val.weight}%)`);
          if (val.reasoning) {
            doc.fontSize(10).fillColor("#666666").text(`  ${val.reasoning}`);
          }
        }
      }
      doc.moveDown();
    }

    // Strengths
    if (analysis.strengths?.length) {
      doc.addPage();
      doc.fontSize(14).fillColor(color).text("Strengths");
      for (const s of analysis.strengths) {
        doc.fontSize(11).fillColor("#333333").text(`• ${s.area}: ${s.detail}`);
      }
      doc.moveDown();
    }

    // Gaps
    if (analysis.gaps?.length && !isExternal) {
      doc.fontSize(14).fillColor(color).text("Gaps & Risks");
      for (const g of analysis.gaps) {
        const sevColor = g.severity === "HIGH" ? "#ef4444" : g.severity === "MEDIUM" ? "#f59e0b" : "#6b7280";
        doc.fontSize(11).fillColor(sevColor).text(`[${g.severity}] ${g.area}`);
        doc.fillColor("#333333").text(`  ${g.detail}`);
      }
      doc.moveDown();
    }

    // Must-have checklist
    if (analysis.mustHaveChecklist?.length) {
      doc.fontSize(14).fillColor(color).text("Requirements Checklist");
      for (const item of analysis.mustHaveChecklist) {
        const icon = item.met ? "✓" : "✗";
        const itemColor = item.met ? "#10b981" : "#ef4444";
        doc.fontSize(11).fillColor(itemColor).text(`${icon} ${item.requirement}`);
        if (item.evidence) {
          doc.fillColor("#666666").text(`  ${item.evidence}`);
        }
      }
      doc.moveDown();
    }

    // Recommendation
    if (analysis.recommendedNextSteps && !isExternal) {
      doc.fontSize(14).fillColor(color).text("Recommendation");
      doc.fontSize(12).fillColor("#333333").text(analysis.recommendedNextSteps);
      doc.moveDown();
    }

    // Interview focus areas
    if (analysis.interviewFocusAreas?.length && !isExternal) {
      doc.fontSize(14).fillColor(color).text("Interview Focus Areas");
      for (const area of analysis.interviewFocusAreas) {
        doc.fontSize(11).fillColor("#333333").text(`• ${area}`);
      }
    }

    // Footer
    doc.fontSize(8).fillColor("#999999");
    doc.text(
      `Generated by ${companyName} via RecruitSmart | ${new Date().toISOString()}`,
      50,
      doc.page.height - 40,
      { align: "center" }
    );

    doc.end();
  });
}

module.exports = { generateCandidateReport };
